# start
>[go to end](#end)

In [1]:
print("its a demo")

its a demo


In [2]:
a=10
b=20

In [3]:
print(a+b)

30


# add a link
>[go to google](www.google.com)

# end
>[go to start](#start)

# Introduction to NumPy

In [4]:
import numpy as np

In [5]:
ar=np.arange(0,11)

In [6]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
ar[6]

6

In [8]:
ar[4:9]

array([4, 5, 6, 7, 8])

compare array

In [9]:
ar>6

array([False, False, False, False, False, False, False,  True,  True,
        True,  True])

In [10]:
type(ar)

numpy.ndarray

2-d array

In [11]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2d[0,0]     #show data at row index 0 and column index 0

1

In [14]:
arr2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [15]:
arr2d=np.arange(50).reshape(5,10)

In [16]:
arr2d     #show the array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [17]:
arr2d[1:3]    #shows the rows from index value 1 to 2

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [19]:
arr2d[6:50]   #range selected is greater, so it will show the range we can select

array([], shape=(0, 10), dtype=int32)

In [18]:
arr2d[1:4,3:7]   #(range of rows,range of column)

array([[13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36]])

apply arithmatic operations on array

In [20]:
ar-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [21]:
ar/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [22]:
ar/ar

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [23]:
np.sqrt(ar)   #print square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [25]:
np.exp(ar)   #print value after their exponent

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [26]:
np.max(ar)    #print maximum value of array

10

In [27]:
np.min(ar)    #print minimum value array

0

In [28]:
np.log(ar)   #print the values after log

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])